# Generated by Django 2.2.24 on 2022-11-16 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EolForumNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('how_often', models.TextField(choices=[('never', 'never'), ('always', 'always'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='never')),
                ('sent_at', models.DateTimeField(default=datetime.date.today)),
                ('comment_created', models.BooleanField(default=False)),
                ('thread_created', models.BooleanField(default=False)),
                ('own_comment_created', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discussion_id', 'user')},
                'index_together': {('discussion_id', 'user')},
            },
        ),
    ]
