# Generated by Django 2.2.24 on 2022-11-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_forum_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolforumnotifications',
            name='discussion_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
