# Generated by Django 2.2.24 on 2023-03-23 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eol_forum_notifications', '0002_auto_20221123_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolForumNotificationsDiscussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.CharField(db_index=True, max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('daily_threads', models.IntegerField(default=0)),
                ('daily_comment', models.IntegerField(default=0)),
                ('weekly_threads', models.IntegerField(default=0)),
                ('weekly_comment', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('discussion_id', 'course_id')},
                'index_together': {('discussion_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='EolForumNotificationsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_often', models.TextField(choices=[('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], default='never')),
                ('sent_at', models.DateTimeField(default=datetime.date.today)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eol_forum_notifications.EolForumNotificationsDiscussions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discussion', 'user')},
                'index_together': {('discussion', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='EolForumNotifications',
        ),
    ]
