# Generated by Django 2.2.24 on 2023-03-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_forum_notifications', '0003_auto_20230323_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eolforumnotificationsuser',
            name='sent_at',
        ),
    ]
