# Generated by Django 2.2.24 on 2023-03-27 19:59

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_forum_notifications', '0004_remove_eolforumnotificationsuser_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolforumnotificationsdiscussions',
            name='block_key',
            field=opaque_keys.edx.django.models.UsageKeyField(default=None, max_length=255),
        ),
    ]
